name: Windows
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout mbedtls
        uses: actions/checkout@v4
        with:
          repository: Mbed-TLS/mbedtls
          ref: v3.2.1
          path: mbedtls
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build mbedtls
        run: |
          cd mbedtls
          mkdir build
          cd build
          cmake .. -DENABLE_TESTING=OFF -DENABLE_PROGRAMS=OFF -DDISABLE_PACKAGE_CONFIG_AND_INSTALL=OFF
          cmake --build . --config Debug
          cmake --install . --config Debug --prefix install/Debug
          cmake --build . --config Release
          cmake --install . --config Release --prefix install/Release
      - name: Generate zip
        run: |
          echo ${{ github.sha }} > Release.txt
          Compress-Archive -Path ./mbedtls/build/install/*,./Release.txt -DestinationPath mbedtls.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: mbedtls.zip